version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PARSE_SERVER_APPLICATION_ID=${PARSE_SERVER_APPLICATION_ID}
      - PARSE_SERVER_MASTER_KEY=${PARSE_SERVER_MASTER_KEY}
      - PARSE_SERVER_DATABASE_URI=${PARSE_SERVER_DATABASE_URI}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
